repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff format .
        language: system
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff-lint
        entry: poetry run ruff check . --fix
        language: system
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: poetry run mypy . --explicit-package-bases
        language: system
        pass_filenames: false
        always_run: true
